# Generated by Django 6.0 on 2025-12-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=80)),
                ('status', models.CharField(choices=[('Sent', 'SENT'), ('Not Sent', 'NOT_SENT'), ('Deleted', 'DELETED')], default=('Not Sent', 'NOT_SENT'))),
                ('body_text', models.TextField(default='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
